# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Jes/'us E. Batta"
description: "Data Analyst and Python Developer"
author:      "Jes/'us E. Batta"
